# Generated by Django 3.2 on 2021-05-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, verbose_name='할일')),
                ('estimated_time', models.CharField(max_length=5, verbose_name='예상 시간')),
                ('complete', models.BooleanField(verbose_name='완료여부')),
                ('memo', models.TextField(verbose_name='메모장')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
