# Generated by Django 3.2 on 2021-05-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='memo',
        ),
    ]
